-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME,CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM  BOOK A 
JOIN AUTHOR B ON A.AUTHOR_ID=B.AUTHOR_ID
JOIN BOOK_SALES Y ON A.BOOK_ID = Y.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-01'
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
